import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { AppLayout } from "@/components/layout/AppLayout";
import { useAppContext } from "@/contexts/AppContext";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Group, User } from "@/types";
import { CURRENCIES } from "@/lib/constants";
import { Search, UserPlus, Users, X } from "lucide-react";
import { getInitials } from "@/lib/utils";

export default function CreateGroup() {
  const navigate = useNavigate();
  const { state, createGroup } = useAppContext();
  const { user: authUser } = useAuth();
  const { users, currentUser } = state;

  // User to use (either from auth or app context)
  const user = authUser || currentUser;

  // Form state
  const [groupName, setGroupName] = useState<string>("");
  const [description, setDescription] = useState<string>("");
  const [defaultCurrency, setDefaultCurrency] = useState<string>("USD");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [selectedMembers, setSelectedMembers] = useState<string[]>([user.id]);
  const [friendEmail, setFriendEmail] = useState<string>("");
  const [friendSID, setFriendSID] = useState<string>("");
  const [errors, setErrors] = useState<{ [key: string]: string }>({});

  // Reset errors when inputs change
  useEffect(() => {
    setErrors({});
  }, [groupName, friendEmail, friendSID]);

  // Filter users based on search query
  const filteredUsers = users.filter(u => {
    if (selectedMembers.includes(u.id)) return false;
    if (!searchQuery.trim()) return true;

    const query = searchQuery.toLowerCase();
    return (
      u.name.toLowerCase().includes(query) ||
      u.email.toLowerCase().includes(query)
    );
  });

  // Handle member selection
  const toggleMember = (userId: string) => {
    if (userId === user.id) return; // Can't remove yourself

    if (selectedMembers.includes(userId)) {
      setSelectedMembers(selectedMembers.filter(id => id !== userId));
    } else {
      setSelectedMembers([...selectedMembers, userId]);
    }
  };

  // Remove a selected member
  const removeMember = (userId: string) => {
    if (userId === user.id) return; // Can't remove yourself
    setSelectedMembers(selectedMembers.filter(id => id !== userId));
  };

  // Handle friend search by email
  const searchFriendByEmail = () => {
    if (!friendEmail.trim()) {
      setErrors({ ...errors, email: "Please enter an email address" });
      return;
    }

    const friendFound = users.find(u =>
      u.email.toLowerCase() === friendEmail.toLowerCase()
    );

    if (friendFound) {
      if (!selectedMembers.includes(friendFound.id)) {
        setSelectedMembers([...selectedMembers, friendFound.id]);
        setFriendEmail("");
      } else {
        setErrors({ ...errors, email: "This user is already added to the group" });
      }
    } else {
      setErrors({ ...errors, email: "No user found with this email address" });
    }
  };

  // Handle friend search by ID
  const searchFriendBySID = () => {
    if (!friendSID.trim()) {
      setErrors({ ...errors, sid: "Please enter a user ID" });
      return;
    }

    const friendFound = users.find(u => u.id === friendSID);

    if (friendFound) {
      if (!selectedMembers.includes(friendFound.id)) {
        setSelectedMembers([...selectedMembers, friendFound.id]);
        setFriendSID("");
      } else {
        setErrors({ ...errors, sid: "This user is already added to the group" });
      }
    } else {
      setErrors({ ...errors, sid: "No user found with this ID" });
    }
  };

  // Create group
  const handleCreateGroup = async () => {
    // Validation
    const newErrors: { [key: string]: string } = {};

    if (!groupName.trim()) {
      newErrors.name = "Group name is required";
    }

    if (selectedMembers.length < 2) {
      newErrors.members = "At least one other member is required";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Create new group
    const newGroupPayload: Group = {
      id: "", // ID will be generated by backend
      name: groupName,
      description: description.trim() || undefined,
      members: selectedMembers,
      createdBy: user.id,
      createdAt: new Date().toISOString(), // Backend expects string or Date? Type says string
      updatedAt: new Date().toISOString(),
      total: 0
    };

    const createdGroup = await createGroup(newGroupPayload);

    if (createdGroup) {
      navigate(`/groups/${createdGroup.id}`);
    }
  };

  // Get selected members data
  const selectedMembersData = selectedMembers
    .map(id => users.find(u => u.id === id))
    .filter(Boolean) as User[];

  return (
    <AppLayout>
      <div className="container mx-auto py-6 px-4">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl md:text-3xl font-bold">Create a New Group</h1>
          <Button variant="outline" onClick={() => navigate("/groups")}>
            Cancel
          </Button>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left column - Group details */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Group Details</CardTitle>
                <CardDescription>
                  Add basic information about your group
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Group name */}
                <div className="space-y-2">
                  <Label htmlFor="name">Group Name<span className="text-destructive">*</span></Label>
                  <Input
                    id="name"
                    placeholder="Roommates, Trip to Paris, Team Lunch..."
                    value={groupName}
                    onChange={(e) => setGroupName(e.target.value)}
                  />
                  {errors.name && (
                    <p className="text-sm text-destructive">{errors.name}</p>
                  )}
                </div>

                {/* Description */}
                <div className="space-y-2">
                  <Label htmlFor="description">Description (Optional)</Label>
                  <Textarea
                    id="description"
                    placeholder="What's this group for?"
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    rows={3}
                  />
                </div>

                {/* Currency */}
                <div className="space-y-2">
                  <Label htmlFor="currency">Default Currency</Label>
                  <Select value={defaultCurrency} onValueChange={setDefaultCurrency}>
                    <SelectTrigger id="currency">
                      <SelectValue placeholder="Select currency" />
                    </SelectTrigger>
                    <SelectContent>
                      {CURRENCIES.map((c) => (
                        <SelectItem key={c.code} value={c.code}>
                          {c.symbol} {c.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Right column - Members */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Group Members</CardTitle>
                <CardDescription>
                  Add friends to your group
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Selected members */}
                <div className="space-y-2">
                  <Label className="flex items-center gap-2">
                    <Users className="h-4 w-4" /> Selected Members ({selectedMembersData.length})
                  </Label>
                  <div className="flex flex-wrap gap-2 border rounded-lg p-2 min-h-12">
                    {selectedMembersData.map((member) => (
                      <div
                        key={member.id}
                        className="flex items-center bg-secondary text-secondary-foreground rounded-full px-3 py-1 text-sm"
                      >
                        <Avatar className="h-5 w-5 mr-1">
                          <AvatarImage src={member.avatar} alt={member.name} />
                          <AvatarFallback>{getInitials(member.name)}</AvatarFallback>
                        </Avatar>
                        <span>{member.id === user.id ? "You" : member.name}</span>
                        {member.id !== user.id && (
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-5 w-5 ml-1 p-0 hover:bg-destructive/20 hover:text-destructive"
                            onClick={() => removeMember(member.id)}
                          >
                            <X className="h-3 w-3" />
                          </Button>
                        )}
                      </div>
                    ))}
                    {selectedMembers.length < 2 && (
                      <p className="text-sm text-muted-foreground">
                        Add at least one person to your group
                      </p>
                    )}
                  </div>
                  {errors.members && (
                    <p className="text-sm text-destructive">{errors.members}</p>
                  )}
                </div>

                {/* Search by email */}
                <div className="space-y-2">
                  <Label htmlFor="email-search">Find Friend by Email</Label>
                  <div className="flex gap-2">
                    <Input
                      id="email-search"
                      type="email"
                      placeholder="friend@example.com"
                      value={friendEmail}
                      onChange={(e) => setFriendEmail(e.target.value)}
                      className="flex-1"
                    />
                    <Button onClick={searchFriendByEmail}>
                      <UserPlus className="h-4 w-4 mr-2" />
                      Add
                    </Button>
                  </div>
                  {errors.email && (
                    <p className="text-sm text-destructive">{errors.email}</p>
                  )}
                </div>

                {/* Search by SID */}
                <div className="space-y-2">
                  <Label htmlFor="sid-search">Find Friend by SID</Label>
                  <div className="flex gap-2">
                    <Input
                      id="sid-search"
                      placeholder="u123..."
                      value={friendSID}
                      onChange={(e) => setFriendSID(e.target.value)}
                      className="flex-1"
                    />
                    <Button onClick={searchFriendBySID}>
                      <UserPlus className="h-4 w-4 mr-2" />
                      Add
                    </Button>
                  </div>
                  {errors.sid && (
                    <p className="text-sm text-destructive">{errors.sid}</p>
                  )}
                </div>

                {/* Browse users */}
                <div className="space-y-2 border-t pt-4">
                  <Label className="flex items-center justify-between">
                    Browse Users
                    <div className="relative w-40">
                      <Search className="absolute left-2 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        placeholder="Search..."
                        className="pl-8"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                      />
                    </div>
                  </Label>
                  <div className="border rounded-lg overflow-hidden">
                    <div className="max-h-60 overflow-y-auto p-1">
                      {filteredUsers.length > 0 ? (
                        filteredUsers.map((user) => (
                          <div
                            key={user.id}
                            className="flex items-center justify-between p-2 hover:bg-accent rounded-md cursor-pointer"
                            onClick={() => toggleMember(user.id)}
                          >
                            <div className="flex items-center gap-3">
                              <Avatar className="h-8 w-8">
                                <AvatarImage src={user.avatar} alt={user.name} />
                                <AvatarFallback>{getInitials(user.name)}</AvatarFallback>
                              </Avatar>
                              <div>
                                <p className="text-sm font-medium">{user.name}</p>
                                <p className="text-xs text-muted-foreground">{user.email}</p>
                              </div>
                            </div>
                            <Checkbox />
                          </div>
                        ))
                      ) : (
                        <div className="p-4 text-center text-sm text-muted-foreground">
                          No users found
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Submit button */}
            <div className="flex justify-end">
              <Button onClick={handleCreateGroup}>
                Create Group
              </Button>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}