import { useState, useEffect } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Checkbox } from "@/components/ui/checkbox";
import { formatCurrency } from "@/lib/utils";
import { useAppContext } from "@/contexts/AppContext";
import { Link } from "react-router-dom";
import { Group, User } from "@/types";
import { PlusCircle, Search } from "lucide-react";

export default function Groups() {
  const { state, createGroup, isLoading } = useAppContext();
  const { groups, users, currentUser } = state;

  // Dialog state
  const [open, setOpen] = useState(false);

  // Form state
  const [groupName, setGroupName] = useState("");
  const [selectedMembers, setSelectedMembers] = useState<string[]>([currentUser.id]);

  // Search state
  const [searchQuery, setSearchQuery] = useState("");
  const [userSearchTerm, setUserSearchTerm] = useState("");
  const [searchResults, setSearchResults] = useState<User[]>([]);
  const [isSearchingUsers, setIsSearchingUsers] = useState(false);

  // Debounced search for users
  useEffect(() => {
    const searchUsers = async () => {
      if (!userSearchTerm.trim()) {
        setSearchResults([]);
        return;
      }

      setIsSearchingUsers(true);
      try {
        const token = localStorage.getItem('token');
        if (!token) {
          setIsSearchingUsers(false);
          return;
        }

        const response = await fetch(`/api/users/search?q=${encodeURIComponent(userSearchTerm)}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (response.ok) {
          const data = await response.json();
          // Filter out current user from results
          setSearchResults(data.filter((u: User) => u.id !== currentUser.id));
        }
      } catch (error) {
        console.error("Failed to search users", error);
      } finally {
        setIsSearchingUsers(false);
      }
    };

    const timeoutId = setTimeout(searchUsers, 500);
    return () => clearTimeout(timeoutId);
  }, [userSearchTerm, currentUser.id]);


  // Create new group
  const handleCreateGroup = async () => {
    if (!groupName.trim()) return;

    const newGroup: Group = {
      id: "", // ID will be generated by backend
      name: groupName,
      members: selectedMembers,
      total: 0,
      createdBy: currentUser.id
    };

    await createGroup(newGroup);

    // Reset form
    setGroupName("");
    setSelectedMembers([currentUser.id]);
    setUserSearchTerm("");
    setSearchResults([]);
    setOpen(false);
  };

  // Toggle member selection
  const toggleMember = (userId: string) => {
    if (userId === currentUser.id) return; // Can't remove yourself

    if (selectedMembers.includes(userId)) {
      setSelectedMembers(selectedMembers.filter(id => id !== userId));
    } else {
      setSelectedMembers([...selectedMembers, userId]);
    }
  };

  // Filter groups by search query
  const filteredGroups = groups.filter(group =>
    group.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Get selected users objects for display logic if needed (optional)
  // But strictly we only need to show search results + selected ones maybe?
  // Current requirement: "Search users... rather than showing users by default"
  // So we show search results.

  return (
    <AppLayout>
      <div className="container mx-auto py-6">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-3xl font-bold">Your Groups</h1>
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button>
                <PlusCircle className="mr-2 h-4 w-4" />
                Create Group
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>Create a New Group</DialogTitle>
                <DialogDescription>
                  Create a group to share expenses with friends, roommates, or family.
                </DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="name" className="col-span-4">
                    Group Name
                  </Label>
                  <Input
                    id="name"
                    placeholder="Weekend Trip, Apartment, etc."
                    className="col-span-4"
                    value={groupName}
                    onChange={(e) => setGroupName(e.target.value)}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label className="col-span-4">Group Members</Label>

                  {/* Single Search Input */}
                  <div className="col-span-4 space-y-2">
                    <Label htmlFor="user-search" className="text-sm">Find Users (Name, Email, or Custom ID)</Label>
                    <div className="relative">
                      <Input
                        id="user-search"
                        placeholder="Search users..."
                        value={userSearchTerm}
                        onChange={(e) => setUserSearchTerm(e.target.value)}
                      />
                      {isSearchingUsers && (
                        <div className="absolute right-3 top-2">
                          <PlusCircle className="animate-spin h-4 w-4 text-muted-foreground" />
                        </div>
                      )}
                    </div>
                  </div>

                  {/* User List - Shows Search Results */}
                  <div className="col-span-4">
                    <Label className="text-sm mb-2 block">
                      {userSearchTerm ? "Search Results:" : "Search to add members:"}
                    </Label>
                    <div className="border rounded-md p-2 max-h-40 overflow-y-auto">
                      {searchResults.length > 0 ? (
                        searchResults.map(user => (
                          <div key={user.id} className="flex items-center space-x-2 p-2 hover:bg-accent rounded-md">
                            <Checkbox
                              id={`user-${user.id}`}
                              checked={selectedMembers.includes(user.id)}
                              onCheckedChange={() => toggleMember(user.id)}
                            />
                            <Label
                              htmlFor={`user-${user.id}`}
                              className="text-sm font-normal cursor-pointer flex items-center gap-2 flex-1"
                            >
                              <Avatar className="h-6 w-6">
                                <AvatarFallback className="text-xs">
                                  {user.name.substring(0, 2).toUpperCase()}
                                </AvatarFallback>
                              </Avatar>
                              <div className="flex flex-col">
                                <span>{user.name}</span>
                                <span className="text-xs text-muted-foreground">{user.email}</span>
                              </div>
                            </Label>
                          </div>
                        ))
                      ) : userSearchTerm && !isSearchingUsers ? (
                        <p className="text-sm text-muted-foreground p-2">No users found.</p>
                      ) : (
                        <p className="text-sm text-muted-foreground p-2">Type to search users...</p>
                      )}
                    </div>

                    {/* Selected Members Summary (Optional but helpful) */}
                    {selectedMembers.length > 1 && (
                      <div className="mt-2">
                        <Label className="text-xs text-muted-foreground">Selected ({selectedMembers.length - 1} added):</Label>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {selectedMembers.filter(id => id !== currentUser.id).map(id => {
                            // We might not have the user object if they weren't in search results recently.
                            // Fallback: check global 'users' from context if available, or just show ID or generic.
                            // Better: Keep a map of selectedUserObjects.
                            // For now, rely on `state.users` which might have them if loaded, or searchResults.
                            const u = users.find(u => u.id === id) || searchResults.find(u => u.id === id);
                            return (
                              <div key={id} className="bg-secondary text-secondary-foreground text-xs px-2 py-1 rounded-full flex items-center gap-1">
                                {u ? u.name : "User"}
                                <span className="cursor-pointer font-bold ml-1 hover:text-destructive" onClick={() => toggleMember(id)}>x</span>
                              </div>
                            )
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>
              <DialogFooter>
                <Button
                  type="submit"
                  onClick={handleCreateGroup}
                  disabled={!groupName.trim()}
                >
                  Create Group
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        <div className="mb-6 relative">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search groups..."
            className="pl-8"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {filteredGroups.length === 0 && (
            <Card className="col-span-full">
              <CardContent className="py-12 text-center">
                <h3 className="text-xl font-semibold mb-2">No groups found</h3>
                <p className="text-muted-foreground mb-6">
                  {searchQuery
                    ? "Try a different search term"
                    : "Start by creating your first group"}
                </p>
                <Button onClick={() => setOpen(true)}>
                  <PlusCircle className="mr-2 h-4 w-4" />
                  Create Group
                </Button>
              </CardContent>
            </Card>
          )}

          {filteredGroups.map((group) => (
            <Link key={group.id} to={`/groups/${group.id}`}>
              <Card className="h-full hover:bg-accent/50 transition-colors cursor-pointer">
                <CardHeader>
                  <CardTitle>{group.name}</CardTitle>
                  <CardDescription>
                    {group.members.length} members
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex justify-between mb-4">
                    <span className="text-sm text-muted-foreground">Total Expenses</span>
                    <span className="font-medium">{formatCurrency(group.total || 0)}</span>
                  </div>

                  <div className="flex -space-x-2">
                    {group.members.slice(0, 4).map((memberId, index) => {
                      const user = users.find(u => u.id === memberId);
                      return (
                        <Avatar key={index} className="h-8 w-8 border-2 border-background">
                          <AvatarFallback className="text-xs bg-primary/10 text-primary">
                            {user?.name.substring(0, 2).toUpperCase()}
                          </AvatarFallback>
                        </Avatar>
                      );
                    })}
                    {group.members.length > 4 && (
                      <Avatar className="h-8 w-8 border-2 border-background">
                        <AvatarFallback className="text-xs bg-muted text-muted-foreground">
                          +{group.members.length - 4}
                        </AvatarFallback>
                      </Avatar>
                    )}
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </AppLayout>
  );
}